export default {

	Login: r => require(['@/components/Login'], r),
	Register: r => require(['@/components/Register'], r),
	Main: r => require(['@/components/Main'], r),
	toDo: r => require(['@/components/toDo'], r),
	test: r => require(['@/components/test'], r),
	Mine: r => require(['@/components/Mine'], r),
	Shopcart: r => require(['@/components/Shopcart'], r),
	Detail: r => require(['@/components/Detail'], r),
	goods: r => require(['@/components/goods'], r),
	Classify: r => require(['@/components/Classify'], r),
	Product1: r => require(['@/components/class/Product1'], r),
	Menu: r => require(['@/components/class/Menu'], r),
	Ny: r => require(['@/components/class/Ny'], r),
	Mz: r => require(['@/components/class/Mz'], r),
	Ps: r => require(['@/components/class/Ps'], r),
	Xp: r => require(['@/components/class/Xp'], r),
	Xb: r => require(['@/components/class/Xb'], r),
	Et: r => require(['@/components/class/Et'], r),
	My: r => require(['@/components/class/My'], r),
	JuJia: r => require(['@/components/class/JuJia'], r),
	MeiShi: r => require(['@/components/class/MeiShi'], r),
	ShuMa: r => require(['@/components/class/ShuMa'], r),
	JiaDian: r => require(['@/components/class/JiaDian'], r),
	Search: r => require(['@/components/Search'], r),
	Order: r => require(['@/components/Order'], r),
	SetUser: r => require(['@/components/SetUser'], r),
	Exit: r => require(['@/components/Exit'], r),
	Member: r => require(['@/components/Member'], r),
	Mcenter: r => require(['@/components/Mcenter'], r),


}